/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/web/wrangler.jsonc --include-runtime=false apps/web/cloudflare-env.d.ts` (hash: 1ccd7ce056d68d0118e7784e94caba6c)
interface __BaseEnv_Env {
	NIVALIS_API: Fetcher /* nivalis-edge-preview */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
