packages:
  - apps/*
  - packages/*

minimumReleaseAgeExclude:
  - "@tanstack/query-core@5.102.0"
  - "@tanstack/react-query@5.102.0"

onlyBuiltDependencies:
  - esbuild
  - sharp

overrides:
  use-sync-external-store: 1.6.0
