/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=infra/providers/cloudflare/edge/wrangler.jsonc --include-runtime=false infra/providers/cloudflare/edge/worker-configuration.d.ts` (hash: 770ed1843c04110c9fa719d8465f712f)
interface __BaseEnv_Env {
	DB: D1Database;
	SYNC_QUEUE: Queue;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
