/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=infra/providers/cloudflare/edge/wrangler.jsonc --include-runtime=false infra/providers/cloudflare/edge/worker-configuration.d.ts` (hash: 3d3fdd145760295159fc1eac24135779)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
