/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=infra/providers/cloudflare/svg/wrangler.jsonc --include-runtime=false infra/providers/cloudflare/svg/worker-configuration.d.ts` (hash: 68718526fefda18d3af3fb87154c7f09)
interface __BaseEnv_Env {
	SITE_URL: "https://aboutme.nivalis.is";
	NIVALIS_API: Fetcher /* nivalis-edge-preview */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL">> {}
}
