/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=infra/providers/cloudflare/svg/wrangler.jsonc --include-runtime=false infra/providers/cloudflare/svg/worker-configuration.d.ts` (hash: 35729b6cd47a9d5b7c4faaa2067631e4)
interface __BaseEnv_Env {
	SVG_CACHE: KVNamespace;
	SITE_URL: "https://aboutme.nivalis.is";
	SVG_PUBLISH_TOKEN: string;
	NIVALIS_API: Fetcher /* nivalis-edge-preview */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "SVG_PUBLISH_TOKEN">> {}
}
